// source: uptick/evm_ibc/v1/query.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
// goog.object.extend(proto, gogoproto_gogo_pb);
var google_api_annotations_pb = require('../../../google/api/annotations_pb.js');
// goog.object.extend(proto, google_api_annotations_pb);
var uptick_evm_ibc_v1_evm_ibc_pb = require('../../../uptick/evm_ibc/v1/evm_ibc_pb.js');
// goog.object.extend(proto, uptick_evm_ibc_v1_evm_ibc_pb);
goog.exportSymbol('proto.uptick.evm_ibc.v1.QueryEvmAddressRequest', null, global);
goog.exportSymbol('proto.uptick.evm_ibc.v1.QueryTokenPairResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.uptick.evm_ibc.v1.QueryEvmAddressRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.displayName = 'proto.uptick.evm_ibc.v1.QueryEvmAddressRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.uptick.evm_ibc.v1.QueryTokenPairResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.uptick.evm_ibc.v1.QueryTokenPairResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.uptick.evm_ibc.v1.QueryTokenPairResponse.displayName = 'proto.uptick.evm_ibc.v1.QueryTokenPairResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.uptick.evm_ibc.v1.QueryEvmAddressRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    port: jspb.Message.getFieldWithDefault(msg, 1, ""),
    channel: jspb.Message.getFieldWithDefault(msg, 2, ""),
    classId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.uptick.evm_ibc.v1.QueryEvmAddressRequest}
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.uptick.evm_ibc.v1.QueryEvmAddressRequest;
  return proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.uptick.evm_ibc.v1.QueryEvmAddressRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.uptick.evm_ibc.v1.QueryEvmAddressRequest}
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPort(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setChannel(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setClassId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.uptick.evm_ibc.v1.QueryEvmAddressRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPort();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getChannel();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getClassId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string port = 1;
 * @return {string}
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.prototype.getPort = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.evm_ibc.v1.QueryEvmAddressRequest} returns this
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.prototype.setPort = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string channel = 2;
 * @return {string}
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.prototype.getChannel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.evm_ibc.v1.QueryEvmAddressRequest} returns this
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.prototype.setChannel = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string class_id = 3;
 * @return {string}
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.prototype.getClassId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.uptick.evm_ibc.v1.QueryEvmAddressRequest} returns this
 */
proto.uptick.evm_ibc.v1.QueryEvmAddressRequest.prototype.setClassId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.uptick.evm_ibc.v1.QueryTokenPairResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.uptick.evm_ibc.v1.QueryTokenPairResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.uptick.evm_ibc.v1.QueryTokenPairResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.evm_ibc.v1.QueryTokenPairResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    tokenPair: (f = msg.getTokenPair()) && uptick_evm_ibc_v1_evm_ibc_pb.TokenPair.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.uptick.evm_ibc.v1.QueryTokenPairResponse}
 */
proto.uptick.evm_ibc.v1.QueryTokenPairResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.uptick.evm_ibc.v1.QueryTokenPairResponse;
  return proto.uptick.evm_ibc.v1.QueryTokenPairResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.uptick.evm_ibc.v1.QueryTokenPairResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.uptick.evm_ibc.v1.QueryTokenPairResponse}
 */
proto.uptick.evm_ibc.v1.QueryTokenPairResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new uptick_evm_ibc_v1_evm_ibc_pb.TokenPair;
      reader.readMessage(value,uptick_evm_ibc_v1_evm_ibc_pb.TokenPair.deserializeBinaryFromReader);
      msg.setTokenPair(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.uptick.evm_ibc.v1.QueryTokenPairResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.uptick.evm_ibc.v1.QueryTokenPairResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.uptick.evm_ibc.v1.QueryTokenPairResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.uptick.evm_ibc.v1.QueryTokenPairResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTokenPair();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      uptick_evm_ibc_v1_evm_ibc_pb.TokenPair.serializeBinaryToWriter
    );
  }
};


/**
 * optional TokenPair token_pair = 1;
 * @return {?proto.uptick.evm_ibc.v1.TokenPair}
 */
proto.uptick.evm_ibc.v1.QueryTokenPairResponse.prototype.getTokenPair = function() {
  return /** @type{?proto.uptick.evm_ibc.v1.TokenPair} */ (
    jspb.Message.getWrapperField(this, uptick_evm_ibc_v1_evm_ibc_pb.TokenPair, 1));
};


/**
 * @param {?proto.uptick.evm_ibc.v1.TokenPair|undefined} value
 * @return {!proto.uptick.evm_ibc.v1.QueryTokenPairResponse} returns this
*/
proto.uptick.evm_ibc.v1.QueryTokenPairResponse.prototype.setTokenPair = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.uptick.evm_ibc.v1.QueryTokenPairResponse} returns this
 */
proto.uptick.evm_ibc.v1.QueryTokenPairResponse.prototype.clearTokenPair = function() {
  return this.setTokenPair(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.uptick.evm_ibc.v1.QueryTokenPairResponse.prototype.hasTokenPair = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.uptick.evm_ibc.v1);
